[project]
name = "2cdm-paperii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.15.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pynbody>=2.4.1",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
]
